### ISSUE TITLE
OutOfMemoryError on (probably) long Device status

### ISSUE THREAD

**Issue by alainbuteau** [tango-controls/jive#50]
Through "Jive -> Tests Device" , when reading the status of a Device ( whose status may be in some occasion quite long (a few hundreds of caracters)) , we have a OutOfMemoryError on jive with the following call stack

[com-mars@srv4 Desktop]$ jive
WARN 2017-01-03 16:51:50,886 [main] org.jacorb.orb.singleton.configureCodeset:208 - Warning - unknown codeset (ASCII) - defaulting to ISO-8859-1
WARN 2017-01-03 16:51:50,891 [main] org.jacorb.orb.configureCodeset:208 - Warning - unknown codeset (ASCII) - defaulting to ISO-8859-1
WARN 2017-01-03 16:51:51,161 [main] org.jacorb.orb.singleton.configureCodeset:208 - Warning - unknown codeset (ASCII) - defaulting to ISO-8859-1

java.lang.NoClassDefFoundError: org/zeromq/ZMQException
Event system will be available only for notifd notification system
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space
at java.util.Arrays.copyOf(Arrays.java:2367)
at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:130)
at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:114)
at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:415)
at java.lang.StringBuffer.append(StringBuffer.java:237)
at jive.CommandPanel.extractData(CommandPanel.java:711)
at jive.CommandPanel.executeCommand(CommandPanel.java:452)
at jive.CommandPanel.actionPerformed(CommandPanel.java:252)
at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
at java.awt.Component.processMouseEvent(Component.java:6516)
at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
at java.awt.Component.processEvent(Component.java:6281)
at java.awt.Container.processEvent(Container.java:2229)
at java.awt.Component.dispatchEventImpl(Component.java:4872)
at java.awt.Container.dispatchEventImpl(Container.java:2287)
at java.awt.Component.dispatchEvent(Component.java:4698)
at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
at java.awt.Container.dispatchEventImpl(Container.java:2273)
at java.awt.Window.dispatchEventImpl(Window.java:2719)
at java.awt.Component.dispatchEvent(Component.java:4698)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:747)
at java.awt.EventQueue.access$300(EventQueue.java:103)
at java.awt.EventQueue$3.run(EventQueue.java:706)
at java.awt.EventQueue$3.run(EventQueue.java:704)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
Discussion

**Comment by alainbuteau** [comment]
jive vesion is 6.12

**Comment by alainbuteau** [comment]
Jean Luc 
Do yo have enough information in this call stack to work on this issue or should we close the ticket because information is not precise enough ?
